# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Vivado_code/rv32i_v2/rv32i_v2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
# IP: The module: 'blk_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/rv32i_v2/rv32i_v2.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Vivado_code/rv32i_v2/rv32i_v2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
# IP: The module: 'blk_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/rv32i_v2/rv32i_v2.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
